FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
COPY ./publish gosh.server/
RUN mkdir -p /gosh.server/img
RUN mkdir -p /gosh.server/img_shared
WORKDIR /gosh.server
ENTRYPOINT ["dotnet", "QuestHelper.Server.dll"]