FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim
COPY ./publish gosh.server/
RUN mkdir -p /gosh.server/img
RUN mkdir -p /gosh.server/img_shared
WORKDIR /gosh.server
ENTRYPOINT ["dotnet", "QuestHelper.Server.dll"]